### PR TITLE
Reverting changes for the MH visit report

### PR DESCRIPTION
**Pull request by jmbabazi**

### CODE REVIEW

**Comment by brandones** [comment]
Why?

**Comment by mogoodrich** [comment]
@brandones the query was hanging the DB and we want to cut a gold for Liberia today so quickly reverting and will reassess aftert the gold.

**Comment by brandones** [comment]
Thanks!

**Comment by brandones** [comment]
Oops, sorry, got hasty with the Merge button, forgot that we do requester-merges. Hope that didn't cause any trouble.

**Pull request merged**
